### ISSUE TITLE
CORS prohibits API calls on your provided Swagger Dashboard

### ISSUE THREAD

**Issue by Sy-D** [kopfsachen-dev/api#21]
Same goes for curls
See the Image for an example
<img width="681" alt="Bildschirmfoto 2022-07-04 um 15 09 12" src="https://user-images.githubusercontent.com/8460326/177161462-2efd050d-83c1-4854-ba67-5b3787c77751.png">

**Comment by eliasgruenewald** [comment]
<img width="649" alt="Screenshot 2022-07-04 at 15 38 49" src="https://user-images.githubusercontent.com/18154624/177166564-47fffb34-f2e7-46d2-94bb-120163876b4c.png">

Try with the `dev` environment.

**Comment by jgraeger** [comment]
CORS exists for a reason and we don’t intend to allow requests from a GitHub page with access for that many people in the live environment. 

You can use OpenAPI to call dev, as the Allow-Origins header is set accordingly. As an alternative, you can setup a local proxy on your computer for the API requests.

I consider this `notabug` and close the issue.
