### ISSUE TITLE
Adjust wiki-service specification

### ISSUE THREAD

**Issue by jgraeger** [kopfsachen-dev/api#8]
Right now, the API for the wiki-service is not RESTful, specifically

- A route for fetching all articles missing (e.g. GET /wiki)
- Creating a new wiki entry should ne require passing a ID on creation via the URL. Instead it should be determined by the service and returned on a successful CREATE request.
- We want to allow editing wiki articles and need an API endpoint for this (e.g. PUT /wiki/{wikiEntryId} )

**Comment by eliasgruenewald** [comment]
<img width="1149" alt="Screenshot 2022-05-17 at 17 02 43" src="https://user-images.githubusercontent.com/18154624/168843798-27de4caf-c4dc-4d11-aa6a-bfb1fa18f37a.png">
